### ISSUE TITLE
Purpose of native api tokenexchange?

### ISSUE THREAD

**Issue by andig** [trocotronic/weconnect#1]
Great work, thank you very much! This repo is the only source I could find that details the new ID vehicles native login flow- much appreciated! 

I've been playing a bit with it and couldn't really find the need for tokenrefreshservice.apps.emea.vwapps.io/exchangeAuthCode. When I remove the request from the flow it seems to  work just as well? It seems the id token obtained here is identical to the identity kit's token.

The api and login flow also apply to Audi, only the initial login steps are different. If interested in the details please let me know.

**Comment by MyGitIT** [comment]
Hi andig,
I'am intrested in the details, my WebAPI is running well, but I want to use the native API. Do you have an running example of the native API? And th information what to change rgarding the Token?
THX MyGitIT

**Comment by trocotronic** [comment]
exchangeAuthCode delivers some tokens that are used by several methods in NativeAPI (get_users actually).
