### ISSUE TITLE
Does it work faster than the app 

### ISSUE THREAD

**Issue by Klausmd5** [trocotronic/weconnect#12]
Hi,
Does it work faster than the app ?
I currntly do not have a subscription because the app takes longer to connect than to walk to the car and check manualy.

So is it faster than the app?

**Comment by trocotronic** [comment]
I doubt, as it uses the same backend as the app.

**Comment by Klausmd5** [comment]
Is the api really so slow that it takes up to 300 seconds to respond? Thats a reaaaaallly long time.

Thanks.
