### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by vegartb** [trocotronic/weconnect#15]
Hi :-)
I am trying to charge my ID4 according to energy prices.... I am first trying to get this example to work, not sucsessfyl :-(💯 
![image](https://user-images.githubusercontent.com/31689505/228775742-db8f7d78-0e08-4d97-a4c4-32b3adf05322.png)

I am trying to find the solution in myVolkswagen to allow API, but I can not find anything. Is something hidden? ...the issue somthing else?
mvh vegar bartnes

**Comment by trocotronic** [comment]
Can you enable logging level to DEBUG and paste what it displays?
On line `12`

`logging.getLogger().setLevel(logging.DEBUG)`
