### ISSUE TITLE
Feature request: set charging speed

### ISSUE THREAD

**Issue by ottoba** [trocotronic/weconnect#2]
I actually implemented this myself, not sure whether you want to add that as well. Has the nice use case to be able to follow your own overproduction of solar energy in your charging speeds. :)

Added to 'WebAPI.py':

    # set maximum charge current in Ampere, allowed values for e-golf: 5, 10, 13, and 'max', beware that you can only change this a number of times, else VW will return 429 error 'too many requests'
    def set_charger_max_current(self, chargerMaxCurrent='max'):
        self.__check_dashboard()
        self.__command('/-/emanager/set-settings', post={ "chargerMaxCurrent": chargerMaxCurrent, "minChargeLimit": None, "climatisationWithoutHVPower": None, "targetTemperature": None })

**Comment by trocotronic** [comment]
Unfortunately WebAPI is deprecated.
