### ISSUE TITLE
No longer possible to login?

### ISSUE THREAD

**Issue by tedpelas** [trocotronic/weconnect#4]
I guess that VW have changed their web page, because now I'm not able to login at all.

```
% python3 example.py
Traceback (most recent call last):
  File "/Users/666/git/weconnect/example.py", line 15, in <module>
    vwc.login(USER,PASSWORD)
  File "/Users/666/git/weconnect/WebAPI.py", line 69, in login
    ng_init = c['ng-init']
TypeError: 'NoneType' object is not subscriptable
```

**Comment by acaranta** [comment]
Apparently VW changed(I guess) a lot of things as they migrated their service to a new name...
Probably URLs changed and maybe the API too ... I wish I could look into it, gotta try to find the time ... even tho I am not even sure I may be able to edit and correct stuff 😅

**Comment by trocotronic** [comment]
Yep, VW has shutdown We Connect's portal. The new portal is myvolkswagen.net and there is a tab named "My garage", with your car in it. However, it does show much less information and it is not possible to control the car anymore. It is pretty useless. From there I can only obtain a report of last trip, a report of car status and manage We Connect subscription (actived devices, smart keys, etc.). Nothing else.

Hopefully, the NativeAPI still works.

**Comment by tedpelas** [comment]
> Hopefully, the NativeAPI still works.

Is it a Native API from Volkswagen?

**Comment by trocotronic** [comment]
> > Hopefully, the NativeAPI still works.
> 
> Is it a Native API from Volkswagen?

It is the same API used by Android/iOS apps.

**Comment by tedpelas** [comment]
Found this after sniffing what destination (tokenrefreshservice.apps.emea.vwapps.io) that app is using:
https://www.gitmemory.com/issue/robinostlund/volkswagencarnet/111/828173958

**Comment by acaranta** [comment]
> (...)However, it does show much less information and it is not possible to control the car anymore. It is pretty useless. From there I can only obtain a report of last trip, a report of car status and manage We Connect subscription (actived devices, smart keys, etc.). Nothing else.

Ah at least I don't feel alone in thinking they absolutely trashed their customer facing website ... it's unbelievable to be honest :/

> Hopefully, the NativeAPI still works.

I hope too, I had just a quick look at thet network accesses when you use the webpage, it seems there are direct api calls (but not sure, 😅 

So right now maybe hopefully, just the authentication portal is the blocking problem ?

**Comment by tedpelas** [comment]
@robinostlund seem to be using the Native API for mobile apps, so I will go for that solution in HA:
* https://github.com/robinostlund/homeassistant-volkswagencarnet
