### ISSUE TITLE
need help to understand the code.

### ISSUE THREAD

**Issue by JimKnopf1503** [trocotronic/weconnect#5]
Hi!
First of all, thanks for the great code.
The native example works for me in the first stages. I have a gas-Touran as the first car in my account, that makes the code crash.

The problem is, I need to code in c++ an I'am not a python guy.
I passed the stage where I send the password.
In the next stage, the identity_kit ist filled with values from r.params but I can't see where the data came from.
In my c++ responses I can't find any of that values, like code ore stat or tokens.
Where are they supposed to be in the clean http responses, at which stage?
This is one of the lines that are not clear for me. What means history? 
` "self.__identities = get_url_params(r.history[-1].url)"`

I would be verry thankfull for help.
Greetings,
Burkhard

**Comment by andig** [comment]
I would suggest to just run the python code and use a proxy to intercept the exchange

**Comment by JimKnopf1503** [comment]
Hi!
Thanks for your answer. I wrote the code for Car-Net already and now trying to adapt the changes because of the shutdown of the web-api.
So I will go on trying to figureout how things working now.
Thanks,
Burkhard

**Comment by JimKnopf1503** [comment]
I managed this step. I cought the fist location, not the one from the last redirection.
